import React, { useRef, useEffect, useState } from 'react';
import BackgroundVideo from '../components/BackgroundVideo';
import { Target, Eye, ShieldCheck, Heart } from 'lucide-react';

const AboutPage: React.FC<{ onNavigate: (page: any) => void }> = ({ onNavigate }) => {
  const [visibleIndexes, setVisibleIndexes] = useState<number[]>([]);
  const timelineRef = useRef<HTMLDivElement>(null);

  const timelineData = [
    { year: "2021", title: "The Foundation", desc: "VCAS 合同会社 was established to bridge Japanese and Indian markets." },
    { year: "2022", title: "Business Expansion", desc: "Expanded services to include comprehensive bilingual IT and HR solutions." },
    { year: "2025 MAR", title: "Series A Funding", desc: "Secured $25M to scale our AI-driven design engine." },
    { year: "2026 NOW", title: "Global Expansion", desc: "Launching the V3 platform to the global market." }
  ];

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          const index = parseInt(entry.target.getAttribute('data-index') || '0');
          setVisibleIndexes(prev => prev.includes(index) ? prev : [...prev, index]);
        }
      });
    }, { threshold: 0.2, rootMargin: '0px 0px -100px 0px' });

    const elements = timelineRef.current?.querySelectorAll('.timeline-item');
    elements?.forEach(el => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  const values = [
    { icon: <Target />, title: "Precision", desc: "We strive for mathematical exactness in every line of code generated by our AI." },
    { icon: <Eye />, title: "Transparency", desc: "Trust is built through visibility. Our processes remain open and accountable." },
    { icon: <ShieldCheck />, title: "Security", desc: "Enterprise-grade safety is not a luxury; it's the core foundation of our tech stack." },
    { icon: <Heart />, title: "Innovation", desc: "Pushing the boundaries of what's possible in the intersection of human and machine." }
  ];



  return (
    <div className="pb-24">
      {/* Header */}
      <section className="relative min-h-[50vh] sm:min-h-[60vh] md:min-h-[70vh] lg:min-h-[80vh] flex items-center justify-center overflow-hidden">
        {/* Video Background */}
        <div className="absolute inset-0 z-0">
          <BackgroundVideo
            src="/aboutus.mp4"
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-navy/80 mix-blend-multiply" />
          <div className="absolute inset-0 bg-gradient-to-b from-navy/90 via-navy/40 to-transparent" />
        </div>

        <div className="container mx-auto px-4 sm:px-6 relative z-10 text-center pt-16 sm:pt-20">
          <div className="text-center text-white">
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4">
              About VCAS
            </h1>
            <p className="text-lg sm:text-xl md:text-2xl opacity-90 max-w-2xl mx-auto">
              Bridging India and Japan with innovative IT solutions
            </p>
          </div>
        </div>
      </section>

      {/* Our Story Content */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-6">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-4xl md:text-5xl font-black mb-8 tracking-tight text-gray-900 text-center">Our <span className="text-primary">Story</span></h2>
            <div className="space-y-6 text-gray-600 text-lg leading-relaxed text-left">
              <p>
                At VCAS, we are committed to providing our clients with top-tier IT consulting and services through transparent and streamlined collaboration. We combine diligence and innovation to turn your ideas into reality, with a strong focus on the Japanese market as a vital bridge between India and Japan, supported by our expertise across Information Technology, Sales & Marketing, and Human Resources, and by bilingual resources experienced in both regions. Our capabilities include Application Development, Web Design, as well as Business Intelligence and Analytics, delivered with strong resource depth and professional rigor.
              </p>
              <p>
                We are proud of our team of dedicated, experienced, and highly proficient industry and market specialists, including bilingual consultants who expertly bridge Indian and Japanese business practices, and who are passionate about exceeding client expectations and meeting diverse requirements. We work closely with our clients to co-create the most effective outcomes and tailored solutions.
              </p>
              <p>
                Our primary focus is on quality and efficiency, and we actively seek new opportunities to serve our clients in Japan, India, and beyond with industry-standard, seamless services. At VCAS, our business consultants provide a clear and comprehensive understanding of your needs in the context of current market trends and shifts—particularly as a bridge between India and Japan—enabling us to deliver optimal services focused on enhancing your operational efficiency.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Mission & Vision */}
      <section className="py-24 bg-muted relative overflow-hidden">
        <div className="container mx-auto px-6 relative z-10">
          <div className="vision-mission-section">

            <div className="vision-box vision-mission-card shadow-xl border border-white/10 relative overflow-hidden group hover:-translate-y-1 transition-all duration-300"
              style={{
                background: 'linear-gradient(rgba(6, 25, 55, 0.88), rgba(10, 45, 95, 0.88)), url("/service.mp4")',
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                backdropFilter: 'blur(6px)',
                WebkitBackdropFilter: 'blur(6px)'
              }}>
              <h3 className="text-3xl font-bold text-white mb-4 tracking-wide">Our Vision</h3>
              <p className="text-lg leading-relaxed" style={{ color: 'rgba(255,255,255,0.9)' }}>
                To provide seamless and streamlined recruitment services, adding more flexibility in the industry, making it easier for businesses to find suitable candidates for the job.
              </p>
            </div>

            <div className="vision-mission-image">
              <img
                src="/vision and mission vcas.png"
                alt="Vision and Mission"
                className="drop-shadow-2xl hover:scale-105 transition-transform duration-500"
              />
            </div>

            <div className="mission-box vision-mission-card shadow-xl border border-white/10 relative overflow-hidden group hover:-translate-y-1 transition-all duration-300"
              style={{
                background: 'linear-gradient(rgba(6, 25, 55, 0.88), rgba(10, 45, 95, 0.88)), url("/service.mp4")',
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                backdropFilter: 'blur(6px)',
                WebkitBackdropFilter: 'blur(6px)'
              }}>
              <h3 className="text-3xl font-bold text-white mb-4 tracking-wide">Our Mission</h3>
              <p className="text-lg leading-relaxed" style={{ color: 'rgba(255,255,255,0.9)' }}>
                VCAS's core mission is to become a proficient source of IT and sales recruitment
                for SMEs and large businesses on a global basis. We are committed to becoming your
                top choice. On top of that, we are also committed to designing and developing
                cutting-edge and robust applications for small businesses to help them stay ahead of
                the curve.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* Core Values */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4 tracking-tight text-gray-900">The Values that Drive <span className="text-primary">Us</span></h2>
            <p className="text-gray-600 text-lg">Founded on principles of excellence and integrity.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {values.map((v, i) => (
              <div key={i} className="
                relative p-8 rounded-3xl border border-gray-100 shadow-md text-center group transition-all duration-300
                bg-white
                md:hover:bg-gradient-to-br md:hover:from-navy md:hover:to-blue-700
                md:hover:shadow-2xl md:hover:shadow-navy/25 md:hover:-translate-y-2 md:hover:border-transparent
                active:scale-[0.98] active:bg-blue-50
              ">
                <div className="
                  w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 transition-all duration-300
                  bg-primary/10 text-primary
                  md:group-hover:bg-white/10 md:group-hover:text-white md:group-hover:scale-110 md:group-hover:shadow-[0_0_20px_rgba(255,255,255,0.3)]
                ">
                  {React.cloneElement(v.icon as React.ReactElement, { className: "w-8 h-8" })}
                </div>
                <h4 className="text-xl font-bold mb-4 transition-colors duration-300 text-gray-900 md:group-hover:text-white">{v.title}</h4>
                <p className="text-sm leading-relaxed transition-colors duration-300 text-gray-600 md:group-hover:text-blue-100">{v.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Timeline Section */}
      <section className="py-24 bg-muted">
        <div className="container mx-auto px-6">
          <h2 className="text-4xl md:text-5xl font-black mb-16 text-center tracking-tight text-gray-900">Our <span className="text-primary">Journey</span></h2>

          <div className="relative max-w-4xl mx-auto pl-8" ref={timelineRef}>
            {/* Background Line */}
            <div className="absolute left-0 top-2 bottom-0 w-0.5 bg-gray-200" />

            {/* Active Progress Line */}
            <div
              className="absolute left-0 top-2 w-0.5 bg-primary transition-all duration-1000 ease-in-out"
              style={{
                height: `${Math.max(0, ...visibleIndexes) / (timelineData.length - 1) * 100}%`,
                maxHeight: 'calc(100% - 24px)'
              }}
            />

            {timelineData.map((item, i) => {
              const isVisible = visibleIndexes.includes(i);
              return (
                <div
                  key={i}
                  data-index={i}
                  className={`timeline-item relative group mb-12 last:mb-0 transition-all duration-700 ease-out ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-12'}`}
                  style={{ transitionDelay: `${i * 100}ms` }}
                >
                  {/* Dot */}
                  <div className={`absolute -left-[41px] top-0 w-4 h-4 rounded-full transition-all duration-500 z-10 
                    ${isVisible ? 'bg-primary scale-125 shadow-lg shadow-primary/30' : 'bg-gray-300 scale-100'}`}
                  />

                  <div className="text-xs font-bold text-primary mb-2 uppercase tracking-widest">{item.year}</div>
                  <h4 className="text-xl font-bold mb-2 text-gray-900">{item.title}</h4>
                  <p className="text-gray-600 group-hover:text-gray-900 transition-colors">{item.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 container mx-auto px-6">
        <div className="p-16 rounded-[40px] bg-navy border border-white/10 text-center relative overflow-hidden group shadow-2xl shadow-navy/50">
          {/* Background Overlay */}
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-blue-900/40 via-navy to-navy pointer-events-none" />

          <div className="relative z-10">
            <h2 className="text-4xl md:text-5xl font-black mb-8 tracking-tight text-white">Ready to Shape the <span className="text-primary">Future?</span></h2>
            <p className="text-xl text-blue-100/80 mb-12 max-w-2xl mx-auto font-light leading-relaxed">
              Join us on our mission to revolutionize the enterprise landscape with autonomous AI solutions.
            </p>
            <div className="flex flex-col sm:flex-row gap-6 justify-center">
              <button
                onClick={() => onNavigate('contact')}
                className="px-8 py-4 rounded-full bg-primary text-white font-bold text-lg flex items-center justify-center gap-2 hover:scale-105 transition-all shadow-xl shadow-black/20 hover:shadow-primary/30"
              >
                Get in Touch
              </button>
              <button
                onClick={() => onNavigate('services')}
                className="px-8 py-4 rounded-full bg-white border border-gray-200 text-gray-900 font-bold text-lg flex items-center justify-center gap-2 hover:bg-gray-50 hover:shadow-lg transition-all"
              >
                Explore Services
              </button>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;
